% ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
%                                                                  
% Hessian - function for Hessian (Jac derivative w.r.t. variables) 
%   Arguments :                                                    
%      V         - Concentrations of variable species (local)      
%      F         - Concentrations of fixed species (local)         
%      RCT       - Rate constants (local)                          
%      HESS      - Hessian of Var (i.e. the 3-tensor d Jac / d Var)
%                                                                  
% ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

% ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
%                                                                  
% Generated by KPP - symbolic chemistry Kinetics PreProcessor      
%     KPP is developed at CGRER labs University of Iowa by         
%     Valeriu Damian & Adrian Sandu                                
%                                                                  
% File                 : cbm_Hessian.m                             
% Time                 : Sun Jan 16 05:53:56 9031                  
% Working directory    : /home/sandu/kpp-2.2.3/examples/Cbm_matlab 
% Equation file        : cbm.kpp                                   
% Output root filename : cbm                                       
%                                                                  
% ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

function  [ HESS ] =  cbm_Hessian ( V , F , RCT )

% --------------------------------------------------------         
% Note: HESS is represented in coordinate sparse format:           
%       HESS(m) = d^2 f_i / dv_j dv_k = d Jac_{i,j} / dv_k         
%       where i = IHESS_I(m), j = IHESS_J(m), k = IHESS_K(m).      
% --------------------------------------------------------         
% Note: d^2 f_i / dv_j dv_k = d^2 f_i / dv_k dv_j,                 
%       therefore only the terms d^2 f_i / dv_j dv_k               
%       with j <= k are computed and stored in HESS.               
% --------------------------------------------------------         

% Computation of the second derivatives of equation rates          
% D2A(1) = d^2 A(3) / dV(25)dV(31)                                 
   D2A(1) = RCT(3) ;
% D2A(2) = d^2 A(4) / dV(26)dV(29)                                 
   D2A(2) = 9.3e-12 ;
% D2A(3) = d^2 A(5) / dV(26)dV(29)                                 
   D2A(3) = RCT(5) ;
% D2A(4) = d^2 A(6) / dV(29)dV(31)                                 
   D2A(4) = RCT(6) ;
% D2A(5) = d^2 A(7) / dV(25)dV(26)                                 
   D2A(5) = RCT(7) ;
% D2A(6) = d^2 A(12) / dV(25)dV(27)                                
   D2A(6) = RCT(12) ;
% D2A(7) = d^2 A(13) / dV(25)dV(28)                                
   D2A(7) = RCT(13) ;
% D2A(8) = d^2 A(15) / dV(30)dV(31)                                
   D2A(8) = RCT(15) ;
% D2A(9) = d^2 A(16) / dV(26)dV(30)                                
   D2A(9) = RCT(16) ;
% D2A(10) = d^2 A(17) / dV(26)dV(30)                               
   D2A(10) = RCT(17) ;
% D2A(11) = d^2 A(20)/{dV(31)dV(31)}                               
   D2A(11) = RCT(20)*2 ;
% D2A(12) = d^2 A(21) / dV(26)dV(31)                               
   D2A(12) = 4.39999e-40*F(1) ;
% D2A(13) = d^2 A(22) / dV(27)dV(31)                               
   D2A(13) = RCT(22) ;
% D2A(14) = d^2 A(24) / dV(9)dV(27)                                
   D2A(14) = 6.6e-12 ;
% D2A(15) = d^2 A(25)/{dV(9)dV(9)}                                 
   D2A(15) = 1e-20*2 ;
% D2A(16) = d^2 A(26) / dV(26)dV(27)                               
   D2A(16) = RCT(26) ;
% D2A(17) = d^2 A(27) / dV(12)dV(27)                               
   D2A(17) = RCT(27) ;
% D2A(18) = d^2 A(28) / dV(28)dV(31)                               
   D2A(18) = RCT(28) ;
% D2A(19) = d^2 A(29) / dV(26)dV(28)                               
   D2A(19) = RCT(29) ;
% D2A(20) = d^2 A(31) / dV(10)dV(27)                               
   D2A(20) = RCT(31) ;
% D2A(21) = d^2 A(32)/{dV(28)dV(28)}                               
   D2A(21) = RCT(32)*2 ;
% D2A(22) = d^2 A(33)/{dV(28)dV(28)}                               
   D2A(22) = RCT(33)*2*F(1) ;
% D2A(23) = d^2 A(35) / dV(2)dV(27)                                
   D2A(23) = RCT(35) ;
% D2A(24) = d^2 A(36) / dV(16)dV(27)                               
   D2A(24) = 2.2e-13 ;
% D2A(25) = d^2 A(37) / dV(21)dV(27)                               
   D2A(25) = 1e-11 ;
% D2A(26) = d^2 A(40) / dV(21)dV(29)                               
   D2A(26) = RCT(40) ;
% D2A(27) = d^2 A(41) / dV(21)dV(30)                               
   D2A(27) = 6.3e-16 ;
% D2A(28) = d^2 A(42) / dV(24)dV(29)                               
   D2A(28) = RCT(42) ;
% D2A(29) = d^2 A(43) / dV(24)dV(27)                               
   D2A(29) = RCT(43) ;
% D2A(30) = d^2 A(44) / dV(24)dV(30)                               
   D2A(30) = 2.5e-15 ;
% D2A(31) = d^2 A(46) / dV(31)dV(32)                               
   D2A(31) = RCT(46) ;
% D2A(32) = d^2 A(47) / dV(26)dV(32)                               
   D2A(32) = RCT(47) ;
% D2A(33) = d^2 A(49)/{dV(32)dV(32)}                               
   D2A(33) = 2e-12*2 ;
% D2A(34) = d^2 A(50) / dV(28)dV(32)                               
   D2A(34) = 6.5e-12 ;
% D2A(35) = d^2 A(52) / dV(20)dV(27)                               
   D2A(35) = 8.1e-13 ;
% D2A(36) = d^2 A(55) / dV(13)dV(26)                               
   D2A(36) = 1.5e-11 ;
% D2A(37) = d^2 A(56) / dV(23)dV(29)                               
   D2A(37) = RCT(56) ;
% D2A(38) = d^2 A(57) / dV(23)dV(27)                               
   D2A(38) = RCT(57) ;
% D2A(39) = d^2 A(58) / dV(23)dV(25)                               
   D2A(39) = RCT(58) ;
% D2A(40) = d^2 A(59) / dV(23)dV(30)                               
   D2A(40) = 7.7e-15 ;
% D2A(41) = d^2 A(60) / dV(17)dV(29)                               
   D2A(41) = RCT(60) ;
% D2A(42) = d^2 A(61) / dV(17)dV(27)                               
   D2A(42) = RCT(61) ;
% D2A(43) = d^2 A(62) / dV(17)dV(25)                               
   D2A(43) = RCT(62) ;
% D2A(44) = d^2 A(63) / dV(5)dV(27)                                
   D2A(44) = RCT(63) ;
% D2A(45) = d^2 A(64) / dV(11)dV(31)                               
   D2A(45) = 8.1e-12 ;
% D2A(46) = d^2 A(66) / dV(14)dV(27)                               
   D2A(46) = 4.1e-11 ;
% D2A(47) = d^2 A(67) / dV(14)dV(30)                               
   D2A(47) = 2.2e-11 ;
% D2A(48) = d^2 A(68) / dV(4)dV(26)                                
   D2A(48) = 1.4e-11 ;
% D2A(49) = d^2 A(69) / dV(7)dV(27)                                
   D2A(49) = RCT(69) ;
% D2A(50) = d^2 A(70) / dV(19)dV(27)                               
   D2A(50) = 3e-11 ;
% D2A(51) = d^2 A(72) / dV(19)dV(25)                               
   D2A(51) = RCT(72) ;
% D2A(52) = d^2 A(73) / dV(15)dV(27)                               
   D2A(52) = 1.7e-11 ;
% D2A(53) = d^2 A(75) / dV(22)dV(29)                               
   D2A(53) = 1.8e-11 ;
% D2A(54) = d^2 A(76) / dV(22)dV(27)                               
   D2A(54) = 9.6e-11 ;
% D2A(55) = d^2 A(77) / dV(22)dV(25)                               
   D2A(55) = 1.2e-17 ;
% D2A(56) = d^2 A(78) / dV(22)dV(30)                               
   D2A(56) = 3.2e-13 ;
% D2A(57) = d^2 A(79) / dV(18)dV(31)                               
   D2A(57) = 8.1e-12 ;
% D2A(58) = d^2 A(80)/{dV(18)dV(18)}                               
   D2A(58) = RCT(80)*2 ;
% D2A(59) = d^2 A(81) / dV(8)dV(31)                                
   D2A(59) = 6.8e-13 ;

% Computation of the Jacobian derivative                           
% HESS(1) = d^2 Vdot(2)/{dV(2)dV(27)} = d^2 Vdot(2)/{dV(27)dV(2)}  
   HESS(1) = -D2A(23) ;
% HESS(2) = d^2 Vdot(2)/{dV(28)dV(28)} = d^2 Vdot(2)/{dV(28)dV(28)}
   HESS(2) = D2A(21)+D2A(22) ;
% HESS(3) = d^2 Vdot(3)/{dV(26)dV(32)} = d^2 Vdot(3)/{dV(32)dV(26)}
   HESS(3) = D2A(32) ;
% HESS(4) = d^2 Vdot(4)/{dV(4)dV(26)} = d^2 Vdot(4)/{dV(26)dV(4)}  
   HESS(4) = -D2A(48) ;
% HESS(5) = d^2 Vdot(4)/{dV(14)dV(27)} = d^2 Vdot(4)/{dV(27)dV(14)}
   HESS(5) = 0.4*D2A(46) ;
% HESS(6) = d^2 Vdot(4)/{dV(14)dV(30)} = d^2 Vdot(4)/{dV(30)dV(14)}
   HESS(6) = D2A(47) ;
% HESS(7) = d^2 Vdot(5)/{dV(5)dV(27)} = d^2 Vdot(5)/{dV(27)dV(5)}  
   HESS(7) = -D2A(44) ;
% HESS(8) = d^2 Vdot(6)/{dV(26)dV(30)} = d^2 Vdot(6)/{dV(30)dV(26)}
   HESS(8) = D2A(10) ;
% HESS(9) = d^2 Vdot(7)/{dV(7)dV(27)} = d^2 Vdot(7)/{dV(27)dV(7)}  
   HESS(9) = -D2A(49) ;
% HESS(10) = d^2 Vdot(8)/{dV(8)dV(31)} = d^2 Vdot(8)/{dV(31)dV(8)} 
   HESS(10) = -D2A(59) ;
% HESS(11) = d^2 Vdot(8)/{dV(20)dV(27)} = d^2 Vdot(8)/{dV(27)dV(20)}
   HESS(11) = 0.13*D2A(35) ;
% HESS(12) = d^2 Vdot(8)/{dV(22)dV(27)} = d^2 Vdot(8)/{dV(27)dV(22)}
   HESS(12) = 0.13*D2A(54) ;
% HESS(13) = d^2 Vdot(8)/{dV(22)dV(30)} = d^2 Vdot(8)/{dV(30)dV(22)}
   HESS(13) = D2A(56) ;
% HESS(14) = d^2 Vdot(8)/{dV(23)dV(29)} = d^2 Vdot(8)/{dV(29)dV(23)}
   HESS(14) = 0.02*D2A(37) ;
% HESS(15) = d^2 Vdot(8)/{dV(23)dV(30)} = d^2 Vdot(8)/{dV(30)dV(23)}
   HESS(15) = 0.09*D2A(40) ;
% HESS(16) = d^2 Vdot(9)/{dV(9)dV(9)} = d^2 Vdot(9)/{dV(9)dV(9)}   
   HESS(16) = -2*D2A(15) ;
% HESS(17) = d^2 Vdot(9)/{dV(9)dV(27)} = d^2 Vdot(9)/{dV(27)dV(9)} 
   HESS(17) = -D2A(14) ;
% HESS(18) = d^2 Vdot(9)/{dV(26)dV(31)} = d^2 Vdot(9)/{dV(31)dV(26)}
   HESS(18) = 2*D2A(12) ;
% HESS(19) = d^2 Vdot(9)/{dV(27)dV(31)} = d^2 Vdot(9)/{dV(31)dV(27)}
   HESS(19) = D2A(13) ;
% HESS(20) = d^2 Vdot(10)/{dV(10)dV(27)} = d^2 Vdot(10)/{dV(27)dV(10)}
   HESS(20) = -D2A(20) ;
% HESS(21) = d^2 Vdot(10)/{dV(26)dV(28)} = d^2 Vdot(10)/{dV(28)dV(26)}
   HESS(21) = D2A(19) ;
% HESS(22) = d^2 Vdot(11)/{dV(5)dV(27)} = d^2 Vdot(11)/{dV(27)dV(5)}
   HESS(22) = 0.56*D2A(44) ;
% HESS(23) = d^2 Vdot(11)/{dV(7)dV(27)} = d^2 Vdot(11)/{dV(27)dV(7)}
   HESS(23) = 0.3*D2A(49) ;
% HESS(24) = d^2 Vdot(11)/{dV(11)dV(31)} = d^2 Vdot(11)/{dV(31)dV(11)}
   HESS(24) = -D2A(45) ;
% HESS(25) = d^2 Vdot(12)/{dV(12)dV(27)} = d^2 Vdot(12)/{dV(27)dV(12)}
   HESS(25) = -D2A(17) ;
% HESS(26) = d^2 Vdot(12)/{dV(14)dV(30)} = d^2 Vdot(12)/{dV(30)dV(14)}
   HESS(26) = D2A(47) ;
% HESS(27) = d^2 Vdot(12)/{dV(21)dV(30)} = d^2 Vdot(12)/{dV(30)dV(21)}
   HESS(27) = D2A(27) ;
% HESS(28) = d^2 Vdot(12)/{dV(24)dV(30)} = d^2 Vdot(12)/{dV(30)dV(24)}
   HESS(28) = D2A(30) ;
% HESS(29) = d^2 Vdot(12)/{dV(26)dV(27)} = d^2 Vdot(12)/{dV(27)dV(26)}
   HESS(29) = D2A(16) ;
% HESS(30) = d^2 Vdot(13)/{dV(13)dV(26)} = d^2 Vdot(13)/{dV(26)dV(13)}
   HESS(30) = -D2A(36) ;
% HESS(31) = d^2 Vdot(13)/{dV(20)dV(27)} = d^2 Vdot(13)/{dV(27)dV(20)}
   HESS(31) = 0.76*D2A(35) ;
% HESS(32) = d^2 Vdot(14)/{dV(5)dV(27)} = d^2 Vdot(14)/{dV(27)dV(5)}
   HESS(32) = 0.36*D2A(44) ;
% HESS(33) = d^2 Vdot(14)/{dV(7)dV(27)} = d^2 Vdot(14)/{dV(27)dV(7)}
   HESS(33) = 0.2*D2A(49) ;
% HESS(34) = d^2 Vdot(14)/{dV(14)dV(27)} = d^2 Vdot(14)/{dV(27)dV(14)}
   HESS(34) = -D2A(46) ;
% HESS(35) = d^2 Vdot(14)/{dV(14)dV(30)} = d^2 Vdot(14)/{dV(30)dV(14)}
   HESS(35) = -D2A(47) ;
% HESS(36) = d^2 Vdot(15)/{dV(7)dV(27)} = d^2 Vdot(15)/{dV(27)dV(7)}
   HESS(36) = 0.8*D2A(49) ;
% HESS(37) = d^2 Vdot(15)/{dV(15)dV(27)} = d^2 Vdot(15)/{dV(27)dV(15)}
   HESS(37) = -D2A(52) ;
% HESS(38) = d^2 Vdot(15)/{dV(19)dV(25)} = d^2 Vdot(15)/{dV(25)dV(19)}
   HESS(38) = 0.2*D2A(51) ;
% HESS(39) = d^2 Vdot(15)/{dV(22)dV(25)} = d^2 Vdot(15)/{dV(25)dV(22)}
   HESS(39) = 0.2*D2A(55) ;
% HESS(40) = d^2 Vdot(15)/{dV(22)dV(27)} = d^2 Vdot(15)/{dV(27)dV(22)}
   HESS(40) = 0.4*D2A(54) ;
% HESS(41) = d^2 Vdot(16)/{dV(16)dV(27)} = d^2 Vdot(16)/{dV(27)dV(16)}
   HESS(41) = -D2A(24) ;
% HESS(42) = d^2 Vdot(16)/{dV(17)dV(25)} = d^2 Vdot(16)/{dV(25)dV(17)}
   HESS(42) = 0.42*D2A(43) ;
% HESS(43) = d^2 Vdot(16)/{dV(17)dV(29)} = d^2 Vdot(16)/{dV(29)dV(17)}
   HESS(43) = D2A(41) ;
% HESS(44) = d^2 Vdot(16)/{dV(19)dV(25)} = d^2 Vdot(16)/{dV(25)dV(19)}
   HESS(44) = 0.69*D2A(51) ;
% HESS(45) = d^2 Vdot(16)/{dV(19)dV(27)} = d^2 Vdot(16)/{dV(27)dV(19)}
   HESS(45) = 2*D2A(50) ;
% HESS(46) = d^2 Vdot(16)/{dV(21)dV(27)} = d^2 Vdot(16)/{dV(27)dV(21)}
   HESS(46) = D2A(25) ;
% HESS(47) = d^2 Vdot(16)/{dV(21)dV(29)} = d^2 Vdot(16)/{dV(29)dV(21)}
   HESS(47) = D2A(26) ;
% HESS(48) = d^2 Vdot(16)/{dV(21)dV(30)} = d^2 Vdot(16)/{dV(30)dV(21)}
   HESS(48) = D2A(27) ;
% HESS(49) = d^2 Vdot(16)/{dV(22)dV(25)} = d^2 Vdot(16)/{dV(25)dV(22)}
   HESS(49) = 0.06*D2A(55) ;
% HESS(50) = d^2 Vdot(16)/{dV(22)dV(29)} = d^2 Vdot(16)/{dV(29)dV(22)}
   HESS(50) = 0.5*D2A(53) ;
% HESS(51) = d^2 Vdot(16)/{dV(23)dV(25)} = d^2 Vdot(16)/{dV(25)dV(23)}
   HESS(51) = 0.33*D2A(39) ;
% HESS(52) = d^2 Vdot(16)/{dV(23)dV(29)} = d^2 Vdot(16)/{dV(29)dV(23)}
   HESS(52) = 0.3*D2A(37) ;
% HESS(53) = d^2 Vdot(17)/{dV(17)dV(25)} = d^2 Vdot(17)/{dV(25)dV(17)}
   HESS(53) = -D2A(43) ;
% HESS(54) = d^2 Vdot(17)/{dV(17)dV(27)} = d^2 Vdot(17)/{dV(27)dV(17)}
   HESS(54) = -D2A(42) ;
% HESS(55) = d^2 Vdot(17)/{dV(17)dV(29)} = d^2 Vdot(17)/{dV(29)dV(17)}
   HESS(55) = -D2A(41) ;
% HESS(56) = d^2 Vdot(17)/{dV(22)dV(25)} = d^2 Vdot(17)/{dV(25)dV(22)}
   HESS(56) = 0.55*D2A(55) ;
% HESS(57) = d^2 Vdot(17)/{dV(22)dV(27)} = d^2 Vdot(17)/{dV(27)dV(22)}
   HESS(57) = D2A(54) ;
% HESS(58) = d^2 Vdot(17)/{dV(22)dV(29)} = d^2 Vdot(17)/{dV(29)dV(22)}
   HESS(58) = 0.45*D2A(53) ;
% HESS(59) = d^2 Vdot(18)/{dV(5)dV(27)} = d^2 Vdot(18)/{dV(27)dV(5)}
   HESS(59) = 0.08*D2A(44) ;
% HESS(60) = d^2 Vdot(18)/{dV(7)dV(27)} = d^2 Vdot(18)/{dV(27)dV(7)}
   HESS(60) = 0.5*D2A(49) ;
% HESS(61) = d^2 Vdot(18)/{dV(14)dV(27)} = d^2 Vdot(18)/{dV(27)dV(14)}
   HESS(61) = 0.6*D2A(46) ;
% HESS(62) = d^2 Vdot(18)/{dV(15)dV(27)} = d^2 Vdot(18)/{dV(27)dV(15)}
   HESS(62) = D2A(52) ;
% HESS(63) = d^2 Vdot(18)/{dV(17)dV(27)} = d^2 Vdot(18)/{dV(27)dV(17)}
   HESS(63) = D2A(42) ;
% HESS(64) = d^2 Vdot(18)/{dV(17)dV(29)} = d^2 Vdot(18)/{dV(29)dV(17)}
   HESS(64) = 0.7*D2A(41) ;
% HESS(65) = d^2 Vdot(18)/{dV(18)dV(18)} = d^2 Vdot(18)/{dV(18)dV(18)}
   HESS(65) = -2*D2A(58) ;
% HESS(66) = d^2 Vdot(18)/{dV(18)dV(31)} = d^2 Vdot(18)/{dV(31)dV(18)}
   HESS(66) = -D2A(57) ;
% HESS(67) = d^2 Vdot(18)/{dV(19)dV(25)} = d^2 Vdot(18)/{dV(25)dV(19)}
   HESS(67) = 0.03*D2A(51) ;
% HESS(68) = d^2 Vdot(18)/{dV(19)dV(27)} = d^2 Vdot(18)/{dV(27)dV(19)}
   HESS(68) = D2A(50) ;
% HESS(69) = d^2 Vdot(18)/{dV(20)dV(27)} = d^2 Vdot(18)/{dV(27)dV(20)}
   HESS(69) = 0.87*D2A(35) ;
% HESS(70) = d^2 Vdot(18)/{dV(22)dV(27)} = d^2 Vdot(18)/{dV(27)dV(22)}
   HESS(70) = D2A(54) ;
% HESS(71) = d^2 Vdot(18)/{dV(22)dV(29)} = d^2 Vdot(18)/{dV(29)dV(22)}
   HESS(71) = 0.5*D2A(53) ;
% HESS(72) = d^2 Vdot(18)/{dV(23)dV(25)} = d^2 Vdot(18)/{dV(25)dV(23)}
   HESS(72) = 0.22*D2A(39) ;
% HESS(73) = d^2 Vdot(18)/{dV(23)dV(27)} = d^2 Vdot(18)/{dV(27)dV(23)}
   HESS(73) = D2A(38) ;
% HESS(74) = d^2 Vdot(18)/{dV(23)dV(29)} = d^2 Vdot(18)/{dV(29)dV(23)}
   HESS(74) = 0.28*D2A(37) ;
% HESS(75) = d^2 Vdot(18)/{dV(23)dV(30)} = d^2 Vdot(18)/{dV(30)dV(23)}
   HESS(75) = 0.91*D2A(40) ;
% HESS(76) = d^2 Vdot(18)/{dV(28)dV(32)} = d^2 Vdot(18)/{dV(32)dV(28)}
   HESS(76) = 0.79*D2A(34) ;
% HESS(77) = d^2 Vdot(18)/{dV(31)dV(32)} = d^2 Vdot(18)/{dV(32)dV(31)}
   HESS(77) = D2A(31) ;
% HESS(78) = d^2 Vdot(18)/{dV(32)dV(32)} = d^2 Vdot(18)/{dV(32)dV(32)}
   HESS(78) = 2*D2A(33) ;
% HESS(79) = d^2 Vdot(19)/{dV(11)dV(31)} = d^2 Vdot(19)/{dV(31)dV(11)}
   HESS(79) = 0.9*D2A(45) ;
% HESS(80) = d^2 Vdot(19)/{dV(14)dV(27)} = d^2 Vdot(19)/{dV(27)dV(14)}
   HESS(80) = 0.3*D2A(46) ;
% HESS(81) = d^2 Vdot(19)/{dV(19)dV(25)} = d^2 Vdot(19)/{dV(25)dV(19)}
   HESS(81) = -D2A(51) ;
% HESS(82) = d^2 Vdot(19)/{dV(19)dV(27)} = d^2 Vdot(19)/{dV(27)dV(19)}
   HESS(82) = -D2A(50) ;
% HESS(83) = d^2 Vdot(20)/{dV(7)dV(27)} = d^2 Vdot(20)/{dV(27)dV(7)}
   HESS(83) = 1.1*D2A(49) ;
% HESS(84) = d^2 Vdot(20)/{dV(20)dV(27)} = d^2 Vdot(20)/{dV(27)dV(20)}
   HESS(84) = -1.11*D2A(35) ;
% HESS(85) = d^2 Vdot(20)/{dV(22)dV(25)} = d^2 Vdot(20)/{dV(25)dV(22)}
   HESS(85) = 0.1*D2A(55) ;
% HESS(86) = d^2 Vdot(20)/{dV(22)dV(29)} = d^2 Vdot(20)/{dV(29)dV(22)}
   HESS(86) = 0.9*D2A(53) ;
% HESS(87) = d^2 Vdot(20)/{dV(23)dV(25)} = d^2 Vdot(20)/{dV(25)dV(23)}
   HESS(87) = -D2A(39) ;
% HESS(88) = d^2 Vdot(20)/{dV(23)dV(27)} = d^2 Vdot(20)/{dV(27)dV(23)}
   HESS(88) = -D2A(38) ;
% HESS(89) = d^2 Vdot(20)/{dV(23)dV(29)} = d^2 Vdot(20)/{dV(29)dV(23)}
   HESS(89) = 0.22*D2A(37) ;
% HESS(90) = d^2 Vdot(20)/{dV(23)dV(30)} = d^2 Vdot(20)/{dV(30)dV(23)}
   HESS(90) = -D2A(40) ;
% HESS(91) = d^2 Vdot(21)/{dV(17)dV(25)} = d^2 Vdot(21)/{dV(25)dV(17)}
   HESS(91) = D2A(43) ;
% HESS(92) = d^2 Vdot(21)/{dV(17)dV(27)} = d^2 Vdot(21)/{dV(27)dV(17)}
   HESS(92) = 1.56*D2A(42) ;
% HESS(93) = d^2 Vdot(21)/{dV(17)dV(29)} = d^2 Vdot(21)/{dV(29)dV(17)}
   HESS(93) = D2A(41) ;
% HESS(94) = d^2 Vdot(21)/{dV(19)dV(25)} = d^2 Vdot(21)/{dV(25)dV(19)}
   HESS(94) = 0.7*D2A(51) ;
% HESS(95) = d^2 Vdot(21)/{dV(19)dV(27)} = d^2 Vdot(21)/{dV(27)dV(19)}
   HESS(95) = D2A(50) ;
% HESS(96) = d^2 Vdot(21)/{dV(21)dV(27)} = d^2 Vdot(21)/{dV(27)dV(21)}
   HESS(96) = -D2A(25) ;
% HESS(97) = d^2 Vdot(21)/{dV(21)dV(29)} = d^2 Vdot(21)/{dV(29)dV(21)}
   HESS(97) = -D2A(26) ;
% HESS(98) = d^2 Vdot(21)/{dV(21)dV(30)} = d^2 Vdot(21)/{dV(30)dV(21)}
   HESS(98) = -D2A(27) ;
% HESS(99) = d^2 Vdot(21)/{dV(22)dV(25)} = d^2 Vdot(21)/{dV(25)dV(22)}
   HESS(99) = D2A(55) ;
% HESS(100) = d^2 Vdot(21)/{dV(22)dV(27)} = d^2 Vdot(21)/{dV(27)dV(22)}
   HESS(100) = D2A(54) ;
% HESS(101) = d^2 Vdot(21)/{dV(23)dV(25)} = d^2 Vdot(21)/{dV(25)dV(23)}
   HESS(101) = 0.74*D2A(39) ;
% HESS(102) = d^2 Vdot(21)/{dV(23)dV(27)} = d^2 Vdot(21)/{dV(27)dV(23)}
   HESS(102) = D2A(38) ;
% HESS(103) = d^2 Vdot(21)/{dV(23)dV(29)} = d^2 Vdot(21)/{dV(29)dV(23)}
   HESS(103) = 0.2*D2A(37) ;
% HESS(104) = d^2 Vdot(21)/{dV(23)dV(30)} = d^2 Vdot(21)/{dV(30)dV(23)}
   HESS(104) = D2A(40) ;
% HESS(105) = d^2 Vdot(21)/{dV(28)dV(32)} = d^2 Vdot(21)/{dV(32)dV(28)}
   HESS(105) = 0.79*D2A(34) ;
% HESS(106) = d^2 Vdot(21)/{dV(31)dV(32)} = d^2 Vdot(21)/{dV(32)dV(31)}
   HESS(106) = D2A(31) ;
% HESS(107) = d^2 Vdot(21)/{dV(32)dV(32)} = d^2 Vdot(21)/{dV(32)dV(32)}
   HESS(107) = 2*D2A(33) ;
% HESS(108) = d^2 Vdot(22)/{dV(22)dV(25)} = d^2 Vdot(22)/{dV(25)dV(22)}
   HESS(108) = -D2A(55) ;
% HESS(109) = d^2 Vdot(22)/{dV(22)dV(27)} = d^2 Vdot(22)/{dV(27)dV(22)}
   HESS(109) = -D2A(54) ;
% HESS(110) = d^2 Vdot(22)/{dV(22)dV(29)} = d^2 Vdot(22)/{dV(29)dV(22)}
   HESS(110) = -D2A(53) ;
% HESS(111) = d^2 Vdot(22)/{dV(22)dV(30)} = d^2 Vdot(22)/{dV(30)dV(22)}
   HESS(111) = -D2A(56) ;
% HESS(112) = d^2 Vdot(23)/{dV(22)dV(29)} = d^2 Vdot(23)/{dV(29)dV(22)}
   HESS(112) = 0.55*D2A(53) ;
% HESS(113) = d^2 Vdot(23)/{dV(23)dV(25)} = d^2 Vdot(23)/{dV(25)dV(23)}
   HESS(113) = -D2A(39) ;
% HESS(114) = d^2 Vdot(23)/{dV(23)dV(27)} = d^2 Vdot(23)/{dV(27)dV(23)}
   HESS(114) = -D2A(38) ;
% HESS(115) = d^2 Vdot(23)/{dV(23)dV(29)} = d^2 Vdot(23)/{dV(29)dV(23)}
   HESS(115) = -D2A(37) ;
% HESS(116) = d^2 Vdot(23)/{dV(23)dV(30)} = d^2 Vdot(23)/{dV(30)dV(23)}
   HESS(116) = -D2A(40) ;
% HESS(117) = d^2 Vdot(24)/{dV(17)dV(27)} = d^2 Vdot(24)/{dV(27)dV(17)}
   HESS(117) = 0.22*D2A(42) ;
% HESS(118) = d^2 Vdot(24)/{dV(19)dV(25)} = d^2 Vdot(24)/{dV(25)dV(19)}
   HESS(118) = 0.03*D2A(51) ;
% HESS(119) = d^2 Vdot(24)/{dV(20)dV(27)} = d^2 Vdot(24)/{dV(27)dV(20)}
   HESS(119) = 0.11*D2A(35) ;
% HESS(120) = d^2 Vdot(24)/{dV(22)dV(25)} = d^2 Vdot(24)/{dV(25)dV(22)}
   HESS(120) = 0.4*D2A(55) ;
% HESS(121) = d^2 Vdot(24)/{dV(22)dV(27)} = d^2 Vdot(24)/{dV(27)dV(22)}
   HESS(121) = 0.2*D2A(54) ;
% HESS(122) = d^2 Vdot(24)/{dV(22)dV(29)} = d^2 Vdot(24)/{dV(29)dV(22)}
   HESS(122) = 0.8*D2A(53) ;
% HESS(123) = d^2 Vdot(24)/{dV(23)dV(25)} = d^2 Vdot(24)/{dV(25)dV(23)}
   HESS(123) = 0.5*D2A(39) ;
% HESS(124) = d^2 Vdot(24)/{dV(23)dV(27)} = d^2 Vdot(24)/{dV(27)dV(23)}
   HESS(124) = D2A(38) ;
% HESS(125) = d^2 Vdot(24)/{dV(23)dV(29)} = d^2 Vdot(24)/{dV(29)dV(23)}
   HESS(125) = 0.63*D2A(37) ;
% HESS(126) = d^2 Vdot(24)/{dV(23)dV(30)} = d^2 Vdot(24)/{dV(30)dV(23)}
   HESS(126) = D2A(40) ;
% HESS(127) = d^2 Vdot(24)/{dV(24)dV(27)} = d^2 Vdot(24)/{dV(27)dV(24)}
   HESS(127) = -D2A(29) ;
% HESS(128) = d^2 Vdot(24)/{dV(24)dV(29)} = d^2 Vdot(24)/{dV(29)dV(24)}
   HESS(128) = -D2A(28) ;
% HESS(129) = d^2 Vdot(24)/{dV(24)dV(30)} = d^2 Vdot(24)/{dV(30)dV(24)}
   HESS(129) = -D2A(30) ;
% HESS(130) = d^2 Vdot(25)/{dV(17)dV(25)} = d^2 Vdot(25)/{dV(25)dV(17)}
   HESS(130) = -D2A(43) ;
% HESS(131) = d^2 Vdot(25)/{dV(19)dV(25)} = d^2 Vdot(25)/{dV(25)dV(19)}
   HESS(131) = -D2A(51) ;
% HESS(132) = d^2 Vdot(25)/{dV(22)dV(25)} = d^2 Vdot(25)/{dV(25)dV(22)}
   HESS(132) = -D2A(55) ;
% HESS(133) = d^2 Vdot(25)/{dV(23)dV(25)} = d^2 Vdot(25)/{dV(25)dV(23)}
   HESS(133) = -D2A(39) ;
% HESS(134) = d^2 Vdot(25)/{dV(25)dV(26)} = d^2 Vdot(25)/{dV(26)dV(25)}
   HESS(134) = -D2A(5) ;
% HESS(135) = d^2 Vdot(25)/{dV(25)dV(27)} = d^2 Vdot(25)/{dV(27)dV(25)}
   HESS(135) = -D2A(6) ;
% HESS(136) = d^2 Vdot(25)/{dV(25)dV(28)} = d^2 Vdot(25)/{dV(28)dV(25)}
   HESS(136) = -D2A(7) ;
% HESS(137) = d^2 Vdot(25)/{dV(25)dV(31)} = d^2 Vdot(25)/{dV(31)dV(25)}
   HESS(137) = -D2A(1) ;
% HESS(138) = d^2 Vdot(26)/{dV(4)dV(26)} = d^2 Vdot(26)/{dV(26)dV(4)}
   HESS(138) = -D2A(48) ;
% HESS(139) = d^2 Vdot(26)/{dV(9)dV(9)} = d^2 Vdot(26)/{dV(9)dV(9)}
   HESS(139) = D2A(15) ;
% HESS(140) = d^2 Vdot(26)/{dV(9)dV(27)} = d^2 Vdot(26)/{dV(27)dV(9)}
   HESS(140) = D2A(14) ;
% HESS(141) = d^2 Vdot(26)/{dV(10)dV(27)} = d^2 Vdot(26)/{dV(27)dV(10)}
   HESS(141) = D2A(20) ;
% HESS(142) = d^2 Vdot(26)/{dV(11)dV(31)} = d^2 Vdot(26)/{dV(31)dV(11)}
   HESS(142) = 0.9*D2A(45) ;
% HESS(143) = d^2 Vdot(26)/{dV(13)dV(26)} = d^2 Vdot(26)/{dV(26)dV(13)}
   HESS(143) = -D2A(36) ;
% HESS(144) = d^2 Vdot(26)/{dV(18)dV(31)} = d^2 Vdot(26)/{dV(31)dV(18)}
   HESS(144) = D2A(57) ;
% HESS(145) = d^2 Vdot(26)/{dV(23)dV(30)} = d^2 Vdot(26)/{dV(30)dV(23)}
   HESS(145) = D2A(40) ;
% HESS(146) = d^2 Vdot(26)/{dV(25)dV(26)} = d^2 Vdot(26)/{dV(26)dV(25)}
   HESS(146) = -D2A(5) ;
% HESS(147) = d^2 Vdot(26)/{dV(25)dV(31)} = d^2 Vdot(26)/{dV(31)dV(25)}
   HESS(147) = D2A(1) ;
% HESS(148) = d^2 Vdot(26)/{dV(26)dV(27)} = d^2 Vdot(26)/{dV(27)dV(26)}
   HESS(148) = -D2A(16) ;
% HESS(149) = d^2 Vdot(26)/{dV(26)dV(28)} = d^2 Vdot(26)/{dV(28)dV(26)}
   HESS(149) = -D2A(19) ;
% HESS(150) = d^2 Vdot(26)/{dV(26)dV(29)} = d^2 Vdot(26)/{dV(29)dV(26)}
   HESS(150) = -D2A(2)-D2A(3) ;
% HESS(151) = d^2 Vdot(26)/{dV(26)dV(30)} = d^2 Vdot(26)/{dV(30)dV(26)}
   HESS(151) = -D2A(10) ;
% HESS(152) = d^2 Vdot(26)/{dV(26)dV(31)} = d^2 Vdot(26)/{dV(31)dV(26)}
   HESS(152) = -D2A(12) ;
% HESS(153) = d^2 Vdot(26)/{dV(26)dV(32)} = d^2 Vdot(26)/{dV(32)dV(26)}
   HESS(153) = -D2A(32) ;
% HESS(154) = d^2 Vdot(26)/{dV(28)dV(31)} = d^2 Vdot(26)/{dV(31)dV(28)}
   HESS(154) = D2A(18) ;
% HESS(155) = d^2 Vdot(26)/{dV(29)dV(31)} = d^2 Vdot(26)/{dV(31)dV(29)}
   HESS(155) = D2A(4) ;
% HESS(156) = d^2 Vdot(26)/{dV(30)dV(31)} = d^2 Vdot(26)/{dV(31)dV(30)}
   HESS(156) = 2*D2A(8) ;
% HESS(157) = d^2 Vdot(26)/{dV(31)dV(31)} = d^2 Vdot(26)/{dV(31)dV(31)}
   HESS(157) = 2*D2A(11) ;
% HESS(158) = d^2 Vdot(26)/{dV(31)dV(32)} = d^2 Vdot(26)/{dV(32)dV(31)}
   HESS(158) = D2A(31) ;
% HESS(159) = d^2 Vdot(27)/{dV(2)dV(27)} = d^2 Vdot(27)/{dV(27)dV(2)}
   HESS(159) = -D2A(23) ;
% HESS(160) = d^2 Vdot(27)/{dV(5)dV(27)} = d^2 Vdot(27)/{dV(27)dV(5)}
   HESS(160) = -D2A(44) ;
% HESS(161) = d^2 Vdot(27)/{dV(7)dV(27)} = d^2 Vdot(27)/{dV(27)dV(7)}
   HESS(161) = -D2A(49) ;
% HESS(162) = d^2 Vdot(27)/{dV(9)dV(27)} = d^2 Vdot(27)/{dV(27)dV(9)}
   HESS(162) = -D2A(14) ;
% HESS(163) = d^2 Vdot(27)/{dV(10)dV(27)} = d^2 Vdot(27)/{dV(27)dV(10)}
   HESS(163) = -D2A(20) ;
% HESS(164) = d^2 Vdot(27)/{dV(12)dV(27)} = d^2 Vdot(27)/{dV(27)dV(12)}
   HESS(164) = -D2A(17) ;
% HESS(165) = d^2 Vdot(27)/{dV(14)dV(27)} = d^2 Vdot(27)/{dV(27)dV(14)}
   HESS(165) = -D2A(46) ;
% HESS(166) = d^2 Vdot(27)/{dV(15)dV(27)} = d^2 Vdot(27)/{dV(27)dV(15)}
   HESS(166) = -D2A(52) ;
% HESS(167) = d^2 Vdot(27)/{dV(16)dV(27)} = d^2 Vdot(27)/{dV(27)dV(16)}
   HESS(167) = -D2A(24) ;
% HESS(168) = d^2 Vdot(27)/{dV(17)dV(27)} = d^2 Vdot(27)/{dV(27)dV(17)}
   HESS(168) = -D2A(42) ;
% HESS(169) = d^2 Vdot(27)/{dV(17)dV(29)} = d^2 Vdot(27)/{dV(29)dV(17)}
   HESS(169) = 0.3*D2A(41) ;
% HESS(170) = d^2 Vdot(27)/{dV(19)dV(25)} = d^2 Vdot(27)/{dV(25)dV(19)}
   HESS(170) = 0.08*D2A(51) ;
% HESS(171) = d^2 Vdot(27)/{dV(19)dV(27)} = d^2 Vdot(27)/{dV(27)dV(19)}
   HESS(171) = -D2A(50) ;
% HESS(172) = d^2 Vdot(27)/{dV(20)dV(27)} = d^2 Vdot(27)/{dV(27)dV(20)}
   HESS(172) = -D2A(35) ;
% HESS(173) = d^2 Vdot(27)/{dV(21)dV(27)} = d^2 Vdot(27)/{dV(27)dV(21)}
   HESS(173) = -D2A(25) ;
% HESS(174) = d^2 Vdot(27)/{dV(21)dV(29)} = d^2 Vdot(27)/{dV(29)dV(21)}
   HESS(174) = D2A(26) ;
% HESS(175) = d^2 Vdot(27)/{dV(22)dV(25)} = d^2 Vdot(27)/{dV(25)dV(22)}
   HESS(175) = 0.1*D2A(55) ;
% HESS(176) = d^2 Vdot(27)/{dV(22)dV(27)} = d^2 Vdot(27)/{dV(27)dV(22)}
   HESS(176) = -D2A(54) ;
% HESS(177) = d^2 Vdot(27)/{dV(23)dV(25)} = d^2 Vdot(27)/{dV(25)dV(23)}
   HESS(177) = 0.1*D2A(39) ;
% HESS(178) = d^2 Vdot(27)/{dV(23)dV(27)} = d^2 Vdot(27)/{dV(27)dV(23)}
   HESS(178) = -D2A(38) ;
% HESS(179) = d^2 Vdot(27)/{dV(23)dV(29)} = d^2 Vdot(27)/{dV(29)dV(23)}
   HESS(179) = 0.2*D2A(37) ;
% HESS(180) = d^2 Vdot(27)/{dV(24)dV(27)} = d^2 Vdot(27)/{dV(27)dV(24)}
   HESS(180) = -D2A(29) ;
% HESS(181) = d^2 Vdot(27)/{dV(24)dV(29)} = d^2 Vdot(27)/{dV(29)dV(24)}
   HESS(181) = D2A(28) ;
% HESS(182) = d^2 Vdot(27)/{dV(25)dV(27)} = d^2 Vdot(27)/{dV(27)dV(25)}
   HESS(182) = -D2A(6) ;
% HESS(183) = d^2 Vdot(27)/{dV(25)dV(28)} = d^2 Vdot(27)/{dV(28)dV(25)}
   HESS(183) = D2A(7) ;
% HESS(184) = d^2 Vdot(27)/{dV(26)dV(27)} = d^2 Vdot(27)/{dV(27)dV(26)}
   HESS(184) = -D2A(16) ;
% HESS(185) = d^2 Vdot(27)/{dV(27)dV(31)} = d^2 Vdot(27)/{dV(31)dV(27)}
   HESS(185) = -D2A(13) ;
% HESS(186) = d^2 Vdot(27)/{dV(28)dV(31)} = d^2 Vdot(27)/{dV(31)dV(28)}
   HESS(186) = D2A(18) ;
% HESS(187) = d^2 Vdot(27)/{dV(28)dV(32)} = d^2 Vdot(27)/{dV(32)dV(28)}
   HESS(187) = 0.79*D2A(34) ;
% HESS(188) = d^2 Vdot(28)/{dV(2)dV(27)} = d^2 Vdot(28)/{dV(27)dV(2)}
   HESS(188) = D2A(23) ;
% HESS(189) = d^2 Vdot(28)/{dV(5)dV(27)} = d^2 Vdot(28)/{dV(27)dV(5)}
   HESS(189) = 0.44*D2A(44) ;
% HESS(190) = d^2 Vdot(28)/{dV(7)dV(27)} = d^2 Vdot(28)/{dV(27)dV(7)}
   HESS(190) = 0.7*D2A(49) ;
% HESS(191) = d^2 Vdot(28)/{dV(11)dV(31)} = d^2 Vdot(28)/{dV(31)dV(11)}
   HESS(191) = 0.9*D2A(45) ;
% HESS(192) = d^2 Vdot(28)/{dV(14)dV(27)} = d^2 Vdot(28)/{dV(27)dV(14)}
   HESS(192) = 0.6*D2A(46) ;
% HESS(193) = d^2 Vdot(28)/{dV(16)dV(27)} = d^2 Vdot(28)/{dV(27)dV(16)}
   HESS(193) = D2A(24) ;
% HESS(194) = d^2 Vdot(28)/{dV(17)dV(25)} = d^2 Vdot(28)/{dV(25)dV(17)}
   HESS(194) = 0.12*D2A(43) ;
% HESS(195) = d^2 Vdot(28)/{dV(17)dV(27)} = d^2 Vdot(28)/{dV(27)dV(17)}
   HESS(195) = D2A(42) ;
% HESS(196) = d^2 Vdot(28)/{dV(17)dV(29)} = d^2 Vdot(28)/{dV(29)dV(17)}
   HESS(196) = 1.7*D2A(41) ;
% HESS(197) = d^2 Vdot(28)/{dV(19)dV(25)} = d^2 Vdot(28)/{dV(25)dV(19)}
   HESS(197) = 0.76*D2A(51) ;
% HESS(198) = d^2 Vdot(28)/{dV(19)dV(27)} = d^2 Vdot(28)/{dV(27)dV(19)}
   HESS(198) = 2*D2A(50) ;
% HESS(199) = d^2 Vdot(28)/{dV(20)dV(27)} = d^2 Vdot(28)/{dV(27)dV(20)}
   HESS(199) = 0.11*D2A(35) ;
% HESS(200) = d^2 Vdot(28)/{dV(21)dV(27)} = d^2 Vdot(28)/{dV(27)dV(21)}
   HESS(200) = D2A(25) ;
% HESS(201) = d^2 Vdot(28)/{dV(21)dV(29)} = d^2 Vdot(28)/{dV(29)dV(21)}
   HESS(201) = D2A(26) ;
% HESS(202) = d^2 Vdot(28)/{dV(21)dV(30)} = d^2 Vdot(28)/{dV(30)dV(21)}
   HESS(202) = D2A(27) ;
% HESS(203) = d^2 Vdot(28)/{dV(22)dV(25)} = d^2 Vdot(28)/{dV(25)dV(22)}
   HESS(203) = 0.44*D2A(55) ;
% HESS(204) = d^2 Vdot(28)/{dV(22)dV(27)} = d^2 Vdot(28)/{dV(27)dV(22)}
   HESS(204) = 0.67*D2A(54) ;
% HESS(205) = d^2 Vdot(28)/{dV(22)dV(29)} = d^2 Vdot(28)/{dV(29)dV(22)}
   HESS(205) = 0.6*D2A(53) ;
% HESS(206) = d^2 Vdot(28)/{dV(23)dV(25)} = d^2 Vdot(28)/{dV(25)dV(23)}
   HESS(206) = 0.44*D2A(39) ;
% HESS(207) = d^2 Vdot(28)/{dV(23)dV(27)} = d^2 Vdot(28)/{dV(27)dV(23)}
   HESS(207) = D2A(38) ;
% HESS(208) = d^2 Vdot(28)/{dV(23)dV(29)} = d^2 Vdot(28)/{dV(29)dV(23)}
   HESS(208) = 0.38*D2A(37) ;
% HESS(209) = d^2 Vdot(28)/{dV(25)dV(27)} = d^2 Vdot(28)/{dV(27)dV(25)}
   HESS(209) = D2A(6) ;
% HESS(210) = d^2 Vdot(28)/{dV(25)dV(28)} = d^2 Vdot(28)/{dV(28)dV(25)}
   HESS(210) = -D2A(7) ;
% HESS(211) = d^2 Vdot(28)/{dV(26)dV(28)} = d^2 Vdot(28)/{dV(28)dV(26)}
   HESS(211) = -D2A(19) ;
% HESS(212) = d^2 Vdot(28)/{dV(28)dV(28)} = d^2 Vdot(28)/{dV(28)dV(28)}
   HESS(212) = -2*D2A(21)-2*D2A(22) ;
% HESS(213) = d^2 Vdot(28)/{dV(28)dV(31)} = d^2 Vdot(28)/{dV(31)dV(28)}
   HESS(213) = -D2A(18) ;
% HESS(214) = d^2 Vdot(28)/{dV(28)dV(32)} = d^2 Vdot(28)/{dV(32)dV(28)}
   HESS(214) = -0.21*D2A(34) ;
% HESS(215) = d^2 Vdot(28)/{dV(31)dV(32)} = d^2 Vdot(28)/{dV(32)dV(31)}
   HESS(215) = D2A(31) ;
% HESS(216) = d^2 Vdot(28)/{dV(32)dV(32)} = d^2 Vdot(28)/{dV(32)dV(32)}
   HESS(216) = 2*D2A(33) ;
% HESS(217) = d^2 Vdot(29)/{dV(17)dV(29)} = d^2 Vdot(29)/{dV(29)dV(17)}
   HESS(217) = -D2A(41) ;
% HESS(218) = d^2 Vdot(29)/{dV(21)dV(29)} = d^2 Vdot(29)/{dV(29)dV(21)}
   HESS(218) = -D2A(26) ;
% HESS(219) = d^2 Vdot(29)/{dV(22)dV(29)} = d^2 Vdot(29)/{dV(29)dV(22)}
   HESS(219) = -D2A(53) ;
% HESS(220) = d^2 Vdot(29)/{dV(23)dV(29)} = d^2 Vdot(29)/{dV(29)dV(23)}
   HESS(220) = -D2A(37) ;
% HESS(221) = d^2 Vdot(29)/{dV(24)dV(29)} = d^2 Vdot(29)/{dV(29)dV(24)}
   HESS(221) = -D2A(28) ;
% HESS(222) = d^2 Vdot(29)/{dV(26)dV(29)} = d^2 Vdot(29)/{dV(29)dV(26)}
   HESS(222) = -D2A(2)-D2A(3) ;
% HESS(223) = d^2 Vdot(29)/{dV(29)dV(31)} = d^2 Vdot(29)/{dV(31)dV(29)}
   HESS(223) = -D2A(4) ;
% HESS(224) = d^2 Vdot(30)/{dV(12)dV(27)} = d^2 Vdot(30)/{dV(27)dV(12)}
   HESS(224) = D2A(17) ;
% HESS(225) = d^2 Vdot(30)/{dV(14)dV(30)} = d^2 Vdot(30)/{dV(30)dV(14)}
   HESS(225) = -D2A(47) ;
% HESS(226) = d^2 Vdot(30)/{dV(21)dV(30)} = d^2 Vdot(30)/{dV(30)dV(21)}
   HESS(226) = -D2A(27) ;
% HESS(227) = d^2 Vdot(30)/{dV(22)dV(30)} = d^2 Vdot(30)/{dV(30)dV(22)}
   HESS(227) = -D2A(56) ;
% HESS(228) = d^2 Vdot(30)/{dV(23)dV(30)} = d^2 Vdot(30)/{dV(30)dV(23)}
   HESS(228) = -D2A(40) ;
% HESS(229) = d^2 Vdot(30)/{dV(24)dV(30)} = d^2 Vdot(30)/{dV(30)dV(24)}
   HESS(229) = -D2A(30) ;
% HESS(230) = d^2 Vdot(30)/{dV(25)dV(26)} = d^2 Vdot(30)/{dV(26)dV(25)}
   HESS(230) = D2A(5) ;
% HESS(231) = d^2 Vdot(30)/{dV(26)dV(29)} = d^2 Vdot(30)/{dV(29)dV(26)}
   HESS(231) = D2A(3) ;
% HESS(232) = d^2 Vdot(30)/{dV(26)dV(30)} = d^2 Vdot(30)/{dV(30)dV(26)}
   HESS(232) = -D2A(9)-D2A(10) ;
% HESS(233) = d^2 Vdot(30)/{dV(30)dV(31)} = d^2 Vdot(30)/{dV(31)dV(30)}
   HESS(233) = -D2A(8) ;
% HESS(234) = d^2 Vdot(31)/{dV(8)dV(31)} = d^2 Vdot(31)/{dV(31)dV(8)}
   HESS(234) = -D2A(59) ;
% HESS(235) = d^2 Vdot(31)/{dV(9)dV(9)} = d^2 Vdot(31)/{dV(9)dV(9)}
   HESS(235) = D2A(15) ;
% HESS(236) = d^2 Vdot(31)/{dV(11)dV(31)} = d^2 Vdot(31)/{dV(31)dV(11)}
   HESS(236) = -D2A(45) ;
% HESS(237) = d^2 Vdot(31)/{dV(18)dV(31)} = d^2 Vdot(31)/{dV(31)dV(18)}
   HESS(237) = -D2A(57) ;
% HESS(238) = d^2 Vdot(31)/{dV(25)dV(31)} = d^2 Vdot(31)/{dV(31)dV(25)}
   HESS(238) = -D2A(1) ;
% HESS(239) = d^2 Vdot(31)/{dV(26)dV(29)} = d^2 Vdot(31)/{dV(29)dV(26)}
   HESS(239) = D2A(2) ;
% HESS(240) = d^2 Vdot(31)/{dV(26)dV(30)} = d^2 Vdot(31)/{dV(30)dV(26)}
   HESS(240) = D2A(9) ;
% HESS(241) = d^2 Vdot(31)/{dV(26)dV(31)} = d^2 Vdot(31)/{dV(31)dV(26)}
   HESS(241) = -D2A(12) ;
% HESS(242) = d^2 Vdot(31)/{dV(27)dV(31)} = d^2 Vdot(31)/{dV(31)dV(27)}
   HESS(242) = -D2A(13) ;
% HESS(243) = d^2 Vdot(31)/{dV(28)dV(31)} = d^2 Vdot(31)/{dV(31)dV(28)}
   HESS(243) = -D2A(18) ;
% HESS(244) = d^2 Vdot(31)/{dV(29)dV(31)} = d^2 Vdot(31)/{dV(31)dV(29)}
   HESS(244) = -D2A(4) ;
% HESS(245) = d^2 Vdot(31)/{dV(30)dV(31)} = d^2 Vdot(31)/{dV(31)dV(30)}
   HESS(245) = -D2A(8) ;
% HESS(246) = d^2 Vdot(31)/{dV(31)dV(31)} = d^2 Vdot(31)/{dV(31)dV(31)}
   HESS(246) = -2*D2A(11) ;
% HESS(247) = d^2 Vdot(31)/{dV(31)dV(32)} = d^2 Vdot(31)/{dV(32)dV(31)}
   HESS(247) = -D2A(31) ;
% HESS(248) = d^2 Vdot(32)/{dV(15)dV(27)} = d^2 Vdot(32)/{dV(27)dV(15)}
   HESS(248) = D2A(52) ;
% HESS(249) = d^2 Vdot(32)/{dV(19)dV(25)} = d^2 Vdot(32)/{dV(25)dV(19)}
   HESS(249) = 0.62*D2A(51) ;
% HESS(250) = d^2 Vdot(32)/{dV(19)dV(27)} = d^2 Vdot(32)/{dV(27)dV(19)}
   HESS(250) = D2A(50) ;
% HESS(251) = d^2 Vdot(32)/{dV(22)dV(27)} = d^2 Vdot(32)/{dV(27)dV(22)}
   HESS(251) = 0.2*D2A(54) ;
% HESS(252) = d^2 Vdot(32)/{dV(24)dV(27)} = d^2 Vdot(32)/{dV(27)dV(24)}
   HESS(252) = D2A(29) ;
% HESS(253) = d^2 Vdot(32)/{dV(24)dV(29)} = d^2 Vdot(32)/{dV(29)dV(24)}
   HESS(253) = D2A(28) ;
% HESS(254) = d^2 Vdot(32)/{dV(24)dV(30)} = d^2 Vdot(32)/{dV(30)dV(24)}
   HESS(254) = D2A(30) ;
% HESS(255) = d^2 Vdot(32)/{dV(26)dV(32)} = d^2 Vdot(32)/{dV(32)dV(26)}
   HESS(255) = -D2A(32) ;
% HESS(256) = d^2 Vdot(32)/{dV(28)dV(32)} = d^2 Vdot(32)/{dV(32)dV(28)}
   HESS(256) = -D2A(34) ;
% HESS(257) = d^2 Vdot(32)/{dV(31)dV(32)} = d^2 Vdot(32)/{dV(32)dV(31)}
   HESS(257) = -D2A(31) ;
% HESS(258) = d^2 Vdot(32)/{dV(32)dV(32)} = d^2 Vdot(32)/{dV(32)dV(32)}
   HESS(258) = -2*D2A(33) ;

   HESS = HESS(:);
      
return

% End of Hessian function                                          
% ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~


