% ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
%                                                                  
% Parameter Definition File                                        
%                                                                  
% Generated by KPP-2.2.3 symbolic chemistry Kinetics PreProcessor  
%       (http://www.cs.vt.edu/~asandu/Software/KPP)                
% KPP is distributed under GPL, the general public licence         
%       (http://www.gnu.org/copyleft/gpl.html)                     
% (C) 1995-1997, V. Damian & A. Sandu, CGRER, Univ. Iowa           
% (C) 1997-2005, A. Sandu, Michigan Tech, Virginia Tech            
%     With important contributions from:                           
%        M. Damian, Villanova University, USA                      
%        R. Sander, Max-Planck Institute for Chemistry, Mainz, Germany
%                                                                  
% File                 : cbm_Parameters.m                          
% Time                 : Fri Mar 15 14:06:05 2013                  
% Working directory    : /home/sandu/kpp-2.2.3/examples/Cbm_matlab 
% Equation file        : cbm.kpp                                   
% Output root filename : cbm                                       
%                                                                  
% ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~




% NSPEC - Number of chemical species                               
 global NSPEC; NSPEC = 33; 
% NVAR - Number of Variable species                                
 global NVAR; NVAR = 32; 
% NVARACT - Number of Active species                               
 global NVARACT; NVARACT = 32; 
% NFIX - Number of Fixed species                                   
 global NFIX; NFIX = 1; 
% NREACT - Number of reactions                                     
 global NREACT; NREACT = 81; 
% NVARST - Starting of variables in conc. vect.                    
 global NVARST; NVARST = 1; 
% NFIXST - Starting of fixed in conc. vect.                        
 global NFIXST; NFIXST = 33; 
% NONZERO - Number of nonzero entries in Jacobian                  
 global NONZERO; NONZERO = 276; 
% LU_NONZERO - Number of nonzero entries in LU factoriz. of Jacobian
 global LU_NONZERO; LU_NONZERO = 300; 
% CNVAR - (NVAR+1) Number of elements in compressed row format     
 global CNVAR; CNVAR = 33; 
% CNEQN - (NREACT+1) Number stoicm elements in compressed col format
 global CNEQN; CNEQN = 82; 
% NHESS - Length of Sparse Hessian                                 
 global NHESS; NHESS = 258; 
% NLOOKAT - Number of species to look at                           
 global NLOOKAT; NLOOKAT = 33; 
% NMONITOR - Number of species to monitor                          
 global NMONITOR; NMONITOR = 3; 
% NMASS - Number of atoms to check mass balance                    
 global NMASS; NMASS = 1; 

% Index declaration for variable species in C and VAR              
%   VAR(ind_spc) = C(ind_spc)                                      

 global ind_O1D; ind_O1D = 1; 
 global ind_H2O2; ind_H2O2 = 2; 
 global ind_PAN; ind_PAN = 3; 
 global ind_CRO; ind_CRO = 4; 
 global ind_TOL; ind_TOL = 5; 
 global ind_N2O5; ind_N2O5 = 6; 
 global ind_XYL; ind_XYL = 7; 
 global ind_XO2N; ind_XO2N = 8; 
 global ind_HONO; ind_HONO = 9; 
 global ind_PNA; ind_PNA = 10; 
 global ind_TO2; ind_TO2 = 11; 
 global ind_HNO3; ind_HNO3 = 12; 
 global ind_ROR; ind_ROR = 13; 
 global ind_CRES; ind_CRES = 14; 
 global ind_MGLY; ind_MGLY = 15; 
 global ind_CO; ind_CO = 16; 
 global ind_ETH; ind_ETH = 17; 
 global ind_XO2; ind_XO2 = 18; 
 global ind_OPEN; ind_OPEN = 19; 
 global ind_PAR; ind_PAR = 20; 
 global ind_HCHO; ind_HCHO = 21; 
 global ind_ISOP; ind_ISOP = 22; 
 global ind_OLE; ind_OLE = 23; 
 global ind_ALD2; ind_ALD2 = 24; 
 global ind_O3; ind_O3 = 25; 
 global ind_NO2; ind_NO2 = 26; 
 global ind_OH; ind_OH = 27; 
 global ind_HO2; ind_HO2 = 28; 
 global ind_O; ind_O = 29; 
 global ind_NO3; ind_NO3 = 30; 
 global ind_NO; ind_NO = 31; 
 global ind_C2O3; ind_C2O3 = 32; 

% Index declaration for fixed species in C                         
%   C(ind_spc)                                                     

 global ind_H2O; ind_H2O = 33; 

% Index declaration for fixed species in FIX                       
%    FIX(indf_spc) = C(ind_spc) = C(NVAR+indf_spc)                 

 global indf_H2O; indf_H2O = 1; 

% NJVRP - Length of sparse Jacobian JVRP                           
 global NJVRP; NJVRP = 134; 

% NSTOICM - Length of Sparse Stoichiometric Matrix                 
 global NSTOICM; NSTOICM = 329; 
