% ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
%                                                                  
% JacReactantProd - Jacobian of Reactant Products vector           
%   Arguments :                                                    
%      V         - Concentrations of variable species (local)      
%      F         - Concentrations of fixed species (local)         
%      JVRP      - d ARP(1:NREACT)/d VAR (1:NVAR)                  
%                                                                  
% ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

% ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
%                                                                  
% Generated by KPP - symbolic chemistry Kinetics PreProcessor      
%     KPP is developed at CGRER labs University of Iowa by         
%     Valeriu Damian & Adrian Sandu                                
%                                                                  
% File                 : cbm_JacReactantProd.m                     
% Time                 : Wed Dec 31 19:00:00 1969                  
% Working directory    : /home/sandu/kpp-2.2.3/examples/Cbm_matlab 
% Equation file        : cbm.kpp                                   
% Output root filename : cbm                                       
%                                                                  
% ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

function  [ JVRP ] =  cbm_JacReactantProd ( V , F )


% Reactant Products in each equation are useful in the             
%    stoichiometric formulation of mass action law                 
% Below we compute the Jacobian of the Reactant Products vector    
%    w.r.t. variable species: d ARP(1:NREACT) / d Var(1:NVAR)      

% JVRP(1) = dARP(1)/dV(26)                                         
   JVRP(1) = 1 ;
% JVRP(2) = dARP(2)/dV(29)                                         
   JVRP(2) = 1 ;
% JVRP(3) = dARP(3)/dV(25)                                         
   JVRP(3) = V(31) ;
% JVRP(4) = dARP(3)/dV(31)                                         
   JVRP(4) = V(25) ;
% JVRP(5) = dARP(4)/dV(26)                                         
   JVRP(5) = V(29) ;
% JVRP(6) = dARP(4)/dV(29)                                         
   JVRP(6) = V(26) ;
% JVRP(7) = dARP(5)/dV(26)                                         
   JVRP(7) = V(29) ;
% JVRP(8) = dARP(5)/dV(29)                                         
   JVRP(8) = V(26) ;
% JVRP(9) = dARP(6)/dV(29)                                         
   JVRP(9) = V(31) ;
% JVRP(10) = dARP(6)/dV(31)                                        
   JVRP(10) = V(29) ;
% JVRP(11) = dARP(7)/dV(25)                                        
   JVRP(11) = V(26) ;
% JVRP(12) = dARP(7)/dV(26)                                        
   JVRP(12) = V(25) ;
% JVRP(13) = dARP(8)/dV(25)                                        
   JVRP(13) = 1 ;
% JVRP(14) = dARP(9)/dV(25)                                        
   JVRP(14) = 1 ;
% JVRP(15) = dARP(10)/dV(1)                                        
   JVRP(15) = 1 ;
% JVRP(16) = dARP(11)/dV(1)                                        
   JVRP(16) = F(1) ;
% JVRP(17) = dARP(12)/dV(25)                                       
   JVRP(17) = V(27) ;
% JVRP(18) = dARP(12)/dV(27)                                       
   JVRP(18) = V(25) ;
% JVRP(19) = dARP(13)/dV(25)                                       
   JVRP(19) = V(28) ;
% JVRP(20) = dARP(13)/dV(28)                                       
   JVRP(20) = V(25) ;
% JVRP(21) = dARP(14)/dV(30)                                       
   JVRP(21) = 1 ;
% JVRP(22) = dARP(15)/dV(30)                                       
   JVRP(22) = V(31) ;
% JVRP(23) = dARP(15)/dV(31)                                       
   JVRP(23) = V(30) ;
% JVRP(24) = dARP(16)/dV(26)                                       
   JVRP(24) = V(30) ;
% JVRP(25) = dARP(16)/dV(30)                                       
   JVRP(25) = V(26) ;
% JVRP(26) = dARP(17)/dV(26)                                       
   JVRP(26) = V(30) ;
% JVRP(27) = dARP(17)/dV(30)                                       
   JVRP(27) = V(26) ;
% JVRP(28) = dARP(18)/dV(6)                                        
   JVRP(28) = F(1) ;
% JVRP(29) = dARP(19)/dV(6)                                        
   JVRP(29) = 1 ;
% JVRP(30) = dARP(20)/dV(31)                                       
   JVRP(30) = 2*V(31) ;
% JVRP(31) = dARP(21)/dV(26)                                       
   JVRP(31) = V(31)*F(1) ;
% JVRP(32) = dARP(21)/dV(31)                                       
   JVRP(32) = V(26)*F(1) ;
% JVRP(33) = dARP(22)/dV(27)                                       
   JVRP(33) = V(31) ;
% JVRP(34) = dARP(22)/dV(31)                                       
   JVRP(34) = V(27) ;
% JVRP(35) = dARP(23)/dV(9)                                        
   JVRP(35) = 1 ;
% JVRP(36) = dARP(24)/dV(9)                                        
   JVRP(36) = V(27) ;
% JVRP(37) = dARP(24)/dV(27)                                       
   JVRP(37) = V(9) ;
% JVRP(38) = dARP(25)/dV(9)                                        
   JVRP(38) = 2*V(9) ;
% JVRP(39) = dARP(26)/dV(26)                                       
   JVRP(39) = V(27) ;
% JVRP(40) = dARP(26)/dV(27)                                       
   JVRP(40) = V(26) ;
% JVRP(41) = dARP(27)/dV(12)                                       
   JVRP(41) = V(27) ;
% JVRP(42) = dARP(27)/dV(27)                                       
   JVRP(42) = V(12) ;
% JVRP(43) = dARP(28)/dV(28)                                       
   JVRP(43) = V(31) ;
% JVRP(44) = dARP(28)/dV(31)                                       
   JVRP(44) = V(28) ;
% JVRP(45) = dARP(29)/dV(26)                                       
   JVRP(45) = V(28) ;
% JVRP(46) = dARP(29)/dV(28)                                       
   JVRP(46) = V(26) ;
% JVRP(47) = dARP(30)/dV(10)                                       
   JVRP(47) = 1 ;
% JVRP(48) = dARP(31)/dV(10)                                       
   JVRP(48) = V(27) ;
% JVRP(49) = dARP(31)/dV(27)                                       
   JVRP(49) = V(10) ;
% JVRP(50) = dARP(32)/dV(28)                                       
   JVRP(50) = 2*V(28) ;
% JVRP(51) = dARP(33)/dV(28)                                       
   JVRP(51) = 2*V(28)*F(1) ;
% JVRP(52) = dARP(34)/dV(2)                                        
   JVRP(52) = 1 ;
% JVRP(53) = dARP(35)/dV(2)                                        
   JVRP(53) = V(27) ;
% JVRP(54) = dARP(35)/dV(27)                                       
   JVRP(54) = V(2) ;
% JVRP(55) = dARP(36)/dV(16)                                       
   JVRP(55) = V(27) ;
% JVRP(56) = dARP(36)/dV(27)                                       
   JVRP(56) = V(16) ;
% JVRP(57) = dARP(37)/dV(21)                                       
   JVRP(57) = V(27) ;
% JVRP(58) = dARP(37)/dV(27)                                       
   JVRP(58) = V(21) ;
% JVRP(59) = dARP(38)/dV(21)                                       
   JVRP(59) = 1 ;
% JVRP(60) = dARP(39)/dV(21)                                       
   JVRP(60) = 1 ;
% JVRP(61) = dARP(40)/dV(21)                                       
   JVRP(61) = V(29) ;
% JVRP(62) = dARP(40)/dV(29)                                       
   JVRP(62) = V(21) ;
% JVRP(63) = dARP(41)/dV(21)                                       
   JVRP(63) = V(30) ;
% JVRP(64) = dARP(41)/dV(30)                                       
   JVRP(64) = V(21) ;
% JVRP(65) = dARP(42)/dV(24)                                       
   JVRP(65) = V(29) ;
% JVRP(66) = dARP(42)/dV(29)                                       
   JVRP(66) = V(24) ;
% JVRP(67) = dARP(43)/dV(24)                                       
   JVRP(67) = V(27) ;
% JVRP(68) = dARP(43)/dV(27)                                       
   JVRP(68) = V(24) ;
% JVRP(69) = dARP(44)/dV(24)                                       
   JVRP(69) = V(30) ;
% JVRP(70) = dARP(44)/dV(30)                                       
   JVRP(70) = V(24) ;
% JVRP(71) = dARP(45)/dV(24)                                       
   JVRP(71) = 1 ;
% JVRP(72) = dARP(46)/dV(31)                                       
   JVRP(72) = V(32) ;
% JVRP(73) = dARP(46)/dV(32)                                       
   JVRP(73) = V(31) ;
% JVRP(74) = dARP(47)/dV(26)                                       
   JVRP(74) = V(32) ;
% JVRP(75) = dARP(47)/dV(32)                                       
   JVRP(75) = V(26) ;
% JVRP(76) = dARP(48)/dV(3)                                        
   JVRP(76) = 1 ;
% JVRP(77) = dARP(49)/dV(32)                                       
   JVRP(77) = 2*V(32) ;
% JVRP(78) = dARP(50)/dV(28)                                       
   JVRP(78) = V(32) ;
% JVRP(79) = dARP(50)/dV(32)                                       
   JVRP(79) = V(28) ;
% JVRP(80) = dARP(51)/dV(27)                                       
   JVRP(80) = 1 ;
% JVRP(81) = dARP(52)/dV(20)                                       
   JVRP(81) = V(27) ;
% JVRP(82) = dARP(52)/dV(27)                                       
   JVRP(82) = V(20) ;
% JVRP(83) = dARP(53)/dV(13)                                       
   JVRP(83) = 1 ;
% JVRP(84) = dARP(54)/dV(13)                                       
   JVRP(84) = 1 ;
% JVRP(85) = dARP(55)/dV(13)                                       
   JVRP(85) = V(26) ;
% JVRP(86) = dARP(55)/dV(26)                                       
   JVRP(86) = V(13) ;
% JVRP(87) = dARP(56)/dV(23)                                       
   JVRP(87) = V(29) ;
% JVRP(88) = dARP(56)/dV(29)                                       
   JVRP(88) = V(23) ;
% JVRP(89) = dARP(57)/dV(23)                                       
   JVRP(89) = V(27) ;
% JVRP(90) = dARP(57)/dV(27)                                       
   JVRP(90) = V(23) ;
% JVRP(91) = dARP(58)/dV(23)                                       
   JVRP(91) = V(25) ;
% JVRP(92) = dARP(58)/dV(25)                                       
   JVRP(92) = V(23) ;
% JVRP(93) = dARP(59)/dV(23)                                       
   JVRP(93) = V(30) ;
% JVRP(94) = dARP(59)/dV(30)                                       
   JVRP(94) = V(23) ;
% JVRP(95) = dARP(60)/dV(17)                                       
   JVRP(95) = V(29) ;
% JVRP(96) = dARP(60)/dV(29)                                       
   JVRP(96) = V(17) ;
% JVRP(97) = dARP(61)/dV(17)                                       
   JVRP(97) = V(27) ;
% JVRP(98) = dARP(61)/dV(27)                                       
   JVRP(98) = V(17) ;
% JVRP(99) = dARP(62)/dV(17)                                       
   JVRP(99) = V(25) ;
% JVRP(100) = dARP(62)/dV(25)                                      
   JVRP(100) = V(17) ;
% JVRP(101) = dARP(63)/dV(5)                                       
   JVRP(101) = V(27) ;
% JVRP(102) = dARP(63)/dV(27)                                      
   JVRP(102) = V(5) ;
% JVRP(103) = dARP(64)/dV(11)                                      
   JVRP(103) = V(31) ;
% JVRP(104) = dARP(64)/dV(31)                                      
   JVRP(104) = V(11) ;
% JVRP(105) = dARP(65)/dV(11)                                      
   JVRP(105) = 1 ;
% JVRP(106) = dARP(66)/dV(14)                                      
   JVRP(106) = V(27) ;
% JVRP(107) = dARP(66)/dV(27)                                      
   JVRP(107) = V(14) ;
% JVRP(108) = dARP(67)/dV(14)                                      
   JVRP(108) = V(30) ;
% JVRP(109) = dARP(67)/dV(30)                                      
   JVRP(109) = V(14) ;
% JVRP(110) = dARP(68)/dV(4)                                       
   JVRP(110) = V(26) ;
% JVRP(111) = dARP(68)/dV(26)                                      
   JVRP(111) = V(4) ;
% JVRP(112) = dARP(69)/dV(7)                                       
   JVRP(112) = V(27) ;
% JVRP(113) = dARP(69)/dV(27)                                      
   JVRP(113) = V(7) ;
% JVRP(114) = dARP(70)/dV(19)                                      
   JVRP(114) = V(27) ;
% JVRP(115) = dARP(70)/dV(27)                                      
   JVRP(115) = V(19) ;
% JVRP(116) = dARP(71)/dV(19)                                      
   JVRP(116) = 1 ;
% JVRP(117) = dARP(72)/dV(19)                                      
   JVRP(117) = V(25) ;
% JVRP(118) = dARP(72)/dV(25)                                      
   JVRP(118) = V(19) ;
% JVRP(119) = dARP(73)/dV(15)                                      
   JVRP(119) = V(27) ;
% JVRP(120) = dARP(73)/dV(27)                                      
   JVRP(120) = V(15) ;
% JVRP(121) = dARP(74)/dV(15)                                      
   JVRP(121) = 1 ;
% JVRP(122) = dARP(75)/dV(22)                                      
   JVRP(122) = V(29) ;
% JVRP(123) = dARP(75)/dV(29)                                      
   JVRP(123) = V(22) ;
% JVRP(124) = dARP(76)/dV(22)                                      
   JVRP(124) = V(27) ;
% JVRP(125) = dARP(76)/dV(27)                                      
   JVRP(125) = V(22) ;
% JVRP(126) = dARP(77)/dV(22)                                      
   JVRP(126) = V(25) ;
% JVRP(127) = dARP(77)/dV(25)                                      
   JVRP(127) = V(22) ;
% JVRP(128) = dARP(78)/dV(22)                                      
   JVRP(128) = V(30) ;
% JVRP(129) = dARP(78)/dV(30)                                      
   JVRP(129) = V(22) ;
% JVRP(130) = dARP(79)/dV(18)                                      
   JVRP(130) = V(31) ;
% JVRP(131) = dARP(79)/dV(31)                                      
   JVRP(131) = V(18) ;
% JVRP(132) = dARP(80)/dV(18)                                      
   JVRP(132) = 2*V(18) ;
% JVRP(133) = dARP(81)/dV(8)                                       
   JVRP(133) = V(31) ;
% JVRP(134) = dARP(81)/dV(31)                                      
   JVRP(134) = V(8) ;
      
return

% End of JacReactantProd function                                  
% ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~


