% ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
%                                                                  
% Initialize - function to initialize concentrations               
%   Arguments :                                                    
%                                                                  
% ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

% ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
%                                                                  
% Generated by KPP - symbolic chemistry Kinetics PreProcessor      
%     KPP is developed at CGRER labs University of Iowa by         
%     Valeriu Damian & Adrian Sandu                                
%                                                                  
% File                 : cbm_Initialize.m                          
% Time                 : Wed Dec 31 19:00:00 1969                  
% Working directory    : /home/sandu/kpp-2.2.3/examples/Cbm_matlab 
% Equation file        : cbm.kpp                                   
% Output root filename : cbm                                       
%                                                                  
% ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

function   cbm_Initialize ( )

global CFACTOR VAR FIX NVAR NFIX
  
  

   CFACTOR = 2.550000e+10 ;

   x = (1.0E-8)*CFACTOR ;
   for i = 1:NVAR
     VAR(i) = x ;
   end

   x = (1.0E-8)*CFACTOR ;
   for i = 1:NFIX
     FIX(i) = x ;
   end  

VAR = [   9.6119e-02
   2.5647e+10
   1.4878e+02
   5.3633e-37
   1.7393e-32
   8.8000e+08
  -8.8775e-95
   6.9283e-04
   2.1582e+09
   7.9569e+08
   3.2230e-37
   1.9300e+13
   1.4688e-08
   6.0655e-34
   8.8350e-36
   1.8972e+12
   5.4341e-50
   4.4938e+07
   3.4284e-34
   3.8194e+00
   2.7652e+10
   4.0701e-53
  -3.4007e-57
   1.2569e-01
   5.4239e+12
   2.6644e+11
   2.3447e+07
   1.7228e+08
   6.0681e+04
   1.3249e+08
   2.2803e+10
   2.2174e-02];
   
   FIX(1) = 3.1875e+18;
   
% constant rate coefficients                                       
   RCONST(4) = 9.3e-12 ;
   RCONST(11) = 2.2e-10 ;
   RCONST(18) = 1.3e-21 ;
   RCONST(21) = 4.39999e-40 ;
   RCONST(24) = 6.6e-12 ;
   RCONST(25) = 1e-20 ;
   RCONST(36) = 2.2e-13 ;
   RCONST(37) = 1e-11 ;
   RCONST(41) = 6.3e-16 ;
   RCONST(44) = 2.5e-15 ;
   RCONST(49) = 2e-12 ;
   RCONST(50) = 6.5e-12 ;
   RCONST(52) = 8.1e-13 ;
   RCONST(54) = 1600 ;
   RCONST(55) = 1.5e-11 ;
   RCONST(59) = 7.7e-15 ;
   RCONST(64) = 8.1e-12 ;
   RCONST(65) = 4.2 ;
   RCONST(66) = 4.1e-11 ;
   RCONST(67) = 2.2e-11 ;
   RCONST(68) = 1.4e-11 ;
   RCONST(70) = 3e-11 ;
   RCONST(73) = 1.7e-11 ;
   RCONST(75) = 1.8e-11 ;
   RCONST(76) = 9.6e-11 ;
   RCONST(77) = 1.2e-17 ;
   RCONST(78) = 3.2e-13 ;
   RCONST(79) = 8.1e-12 ;
   RCONST(81) = 6.8e-13 ;
% END constant rate coefficients                                   

% INLINED initializations                                          

   TSTART = 12.0*3600.0;
   TEND = TSTART + 36.0*3600.0;
   DT = 3600.0;
   TEMP = 288.15;

% End INLINED initializations                                      

   VAR = VAR(:);
   FIX = FIX(:);

      
return

% End of Initialize function                                       
% ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~


