% ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
%                                                                  
% Update_PHOTO - function to update photolytical rate constants    
%   Arguments :                                                    
%                                                                  
% ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

% ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
%                                                                  
% Generated by KPP - symbolic chemistry Kinetics PreProcessor      
%     KPP is developed at CGRER labs University of Iowa by         
%     Valeriu Damian & Adrian Sandu                                
%                                                                  
% File                 : cbm_Update_PHOTO.m                        
% Time                 : Wed Dec 31 19:00:00 1969                  
% Working directory    : /home/sandu/kpp-2.2.3/examples/Cbm_matlab 
% Equation file        : cbm.kpp                                   
% Output root filename : cbm                                       
%                                                                  
% ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

function   cbm_Update_PHOTO ( )

global SUN TEMP RCONST

   RCONST(1) = (8.89E-3*SUN) ;
   RCONST(8) = (3.556E-04*SUN) ;
   RCONST(9) = (2.489E-05*SUN) ;
   RCONST(14) = (1.378E-01*SUN) ;
   RCONST(23) = (1.511e-03*SUN) ;
   RCONST(34) = (6.312E-06*SUN) ;
   RCONST(38) = (2.845E-05*SUN) ;
   RCONST(39) = (3.734E-05*SUN) ;
   RCONST(45) = (4.00E-06*SUN) ;
   RCONST(71) = (5.334E-05*SUN) ;
   RCONST(74) = (1.654E-04*SUN) ;
      
return

% End of Update_PHOTO function                                     
% ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~


