% ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
%                                                                  
% Shuffle_user2kpp - function to copy concentrations from USER to KPP
%   Arguments :                                                    
%      V_USER    - Concentration of variable species in USER's order
%      V         - Concentrations of variable species (local)      
%                                                                  
% ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

% ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
%                                                                  
% Generated by KPP - symbolic chemistry Kinetics PreProcessor      
%     KPP is developed at CGRER labs University of Iowa by         
%     Valeriu Damian & Adrian Sandu                                
%                                                                  
% File                 : cbm_Shuffle_user2kpp.m                    
% Time                 : Wed Dec 31 19:00:00 1969                  
% Working directory    : /home/sandu/kpp-2.2.3/examples/Cbm_matlab 
% Equation file        : cbm.kpp                                   
% Output root filename : cbm                                       
%                                                                  
% ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

function  [ V ] =  cbm_Shuffle_user2kpp ( V_USER )

   V(31) = V_USER(1) ;
   V(26) = V_USER(2) ;
   V(30) = V_USER(3) ;
   V(6) = V_USER(4) ;
   V(9) = V_USER(5) ;
   V(12) = V_USER(6) ;
   V(10) = V_USER(7) ;
   V(1) = V_USER(8) ;
   V(29) = V_USER(9) ;
   V(27) = V_USER(10) ;
   V(25) = V_USER(11) ;
   V(28) = V_USER(12) ;
   V(2) = V_USER(13) ;
   V(21) = V_USER(14) ;
   V(24) = V_USER(15) ;
   V(32) = V_USER(16) ;
   V(3) = V_USER(17) ;
   V(20) = V_USER(18) ;
   V(13) = V_USER(19) ;
   V(23) = V_USER(20) ;
   V(17) = V_USER(21) ;
   V(5) = V_USER(22) ;
   V(14) = V_USER(23) ;
   V(11) = V_USER(24) ;
   V(4) = V_USER(25) ;
   V(19) = V_USER(26) ;
   V(7) = V_USER(27) ;
   V(15) = V_USER(28) ;
   V(22) = V_USER(29) ;
   V(18) = V_USER(30) ;
   V(8) = V_USER(31) ;
   V(16) = V_USER(32) ;
      
return

% End of Shuffle_user2kpp function                                 
% ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~


