% ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
%                                                                  
% Utility Data Definition File                                     
%                                                                  
% Generated by KPP-2.2.3 symbolic chemistry Kinetics PreProcessor  
%       (http://www.cs.vt.edu/~asandu/Software/KPP)                
% KPP is distributed under GPL, the general public licence         
%       (http://www.gnu.org/copyleft/gpl.html)                     
% (C) 1995-1997, V. Damian & A. Sandu, CGRER, Univ. Iowa           
% (C) 1997-2005, A. Sandu, Michigan Tech, Virginia Tech            
%     With important contributions from:                           
%        M. Damian, Villanova University, USA                      
%        R. Sander, Max-Planck Institute for Chemistry, Mainz, Germany
%                                                                  
% File                 : cbm_Monitor.m                             
% Time                 : Fri Mar 15 14:06:05 2013                  
% Working directory    : /home/sandu/kpp-2.2.3/examples/Cbm_matlab 
% Equation file        : cbm.kpp                                   
% Output root filename : cbm                                       
%                                                                  
% ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~





SPC_NAMES = [ ... 
'         O1D';'        H2O2';'         PAN'; ... 
'         CRO';'         TOL';'        N2O5'; ... 
'         XYL';'        XO2N';'        HONO'; ... 
'         PNA';'         TO2';'        HNO3'; ... 
'         ROR';'        CRES';'        MGLY'; ... 
'          CO';'         ETH';'         XO2'; ... 
'        OPEN';'         PAR';'        HCHO'; ... 
'        ISOP';'         OLE';'        ALD2'; ... 
'          O3';'         NO2';'          OH'; ... 
'         HO2';'           O';'         NO3'; ... 
'          NO';'        C2O3';'         H2O' ];

LOOKAT = [ ... 
   1;   2;   3;   4;   5;   6;   7;   8;   9;  10;  11;  12; ... 
  13;  14;  15;  16;  17;  18;  19;  20;  21;  22;  23;  24; ... 
  25;  26;  27;  28;  29;  30;  31;  32;  33 ];

MONITOR = [ 25; 26; 31 ];

SMASS = [  ];

EQN_NAMES = [ ];
% INLINED global variables                                         

% End INLINED global variables                                     

